### ISSUE TITLE
method not found in `ImageBuffer<Rgb<u8>, Vec<u8>>`

### ISSUE THREAD

**Issue by ashsingh21** [rust-cv/nshare#10]
I am trying out this example
```
use image::RgbImage;
use nshare::ToNdarray3;
use ndarray::s;

let zeros = RgbImage::new(2, 4);
let mut nd = zeros.into_ndarray3();
nd.fill(255);
// ndarray uses (channel, row, col), so the dims get flipped.
assert_eq!(nd.dim(), (3, 4, 2));
```
but I keep getting this error `method not found in `ImageBuffer<Rgb<u8>, Vec<u8>>`` even though the trait is imported.
Could you help me understand what's wrong?

My cargo.toml
```
ndarray = {version ="0.15.4"}
nshare = {version = "0.8.0", features = ["ndarray", "image"]}
image = "0.24.0"
```

rustc version - `rustc 1.61.0 (fe5b13d68 2022-05-18)`

Thanks

**Comment by xd009642** [comment]
nshare 0.8.0 uses image 0.23 and ndarray 0.15. So looks like it's the image version mismatch (the trait is implemented for RgbImage on image:0.24 which is a different type)

**Comment by xd009642** [comment]
Upgrading to nshare 0.9.0 should hopefully fix it

**Comment by ashsingh21** [comment]
It works after upgrading to 0.9.0. Thanks
