### ISSUE TITLE
Less strict dependencies

### ISSUE THREAD

**Issue by AzHicham** [rust-cv/nshare#14]
Hello, 

Thank you for this library! 
Would it be possible to set less strict dependencies ? 
ie have 
```
ndarray = { version = "0.15", default-features = false, optional = true }
nalgebra = { version = "0.30", default-features = false, optional = true }
image = { version = "0.24", default-features = false, optional = true }
```
instead of 
```
ndarray = { version = "0.15.4", default-features = false, optional = true }
nalgebra = { version = "0.30.1", default-features = false, optional = true }
image = { version = "0.24.0", default-features = false, optional = true }
```

In order to avoid conflict (especially with onnxruntime 0.16) 

Thank you

**Comment by jonaspleyer** [comment]
I would be interested in such a feature too. Right now this prohibits me from actively using this crate since I rely on a dependency with nalgebra version not available by nshare.
